### ISSUE TITLE
Airbnb 메인 페이지 Markup 작업

### ISSUE THREAD

**Issue by grace7937** [peter-house/airbnb-web#5]
Airbnb 메인 페이지를 Clone 하여 Markup 합니다.(https://www.airbnb.co.kr/)

**Comment by livelikeabel** [comment]
해당 페이지 마크업을 전부 하기에는 사이즈가 너무 큰것 같은데, 피쳐를 나누어서 하는건 어떠세요?

**Comment by livelikeabel** [comment]
어떤 UI를 작업할것인지 좀 더 상세하게 이슈를 작성하고 가능하면 스크린샷도 추가해주세요
가능한 300라인 언더로 PR을 날리면 좋겠습니다 @grace7937

**Comment by grace7937** [comment]
@livelikeabel  마크업 전체 PR 날리려면 양이 상당하겠네요! 말씀해 주신대로 피쳐를 나누어서 다시 이슈생성 하겠습니다. :) @livelikeabel

**Comment by livelikeabel** [comment]
죠습니다!
